[operation]
threshold = 1e-6
rng_seed = 1

[calibration.initialisation]

[calibration.domains]
rme_domain = "C:/AIMS/Datasets/ADRIA DataPackages/rme_ml_2025_09_03"

[calibration.geospatial]
canonical_path = "C:/AIMS/Datasets/rrap_canonical_2025-07-15-T10-48-29.gpkg"

[calibration.outputs]
out_dir = "C:/AIMS/calib_results/test"
