# Manual entry point (NOT included by main.jl): computes the EXACT literal-numeric sampling
# bounds used by the sensitivity analysis, for Table S11 in paper.qmd. Rule-based bounds
# quoted directly in Table S11 (e.g. "+/- 10% of nominal values", which differ per
# functional group/size class) are NOT computed here - they're true by construction and
# carry no drift risk. The bounds that ARE worth precomputing are the ones that are a single
# literal (lo, hi) pair, since those can silently go stale if SAConfig/samples.jl change
# without the manuscript being updated to match (this happened at least twice already: the
# hand-typed Reef depth and Initial relative cover rows both drifted from reality).
#
# Mirrors src/sensitivity_analysis/01_run_sa.jl's domain setup exactly (same factor fixes,
# same dist_mean bound override), so the bounds extracted from ADRIA.model_spec(dom) match
# what the sensitivity analysis actually samples over - not a separately-configured domain.
#
#   julia --project=. src/outcomes/sensitivity_analysis_factors.jl
using ADRIA
using DataFrames
using TOML

const SRC_DIR = dirname(@__DIR__)
include(joinpath(SRC_DIR, "sensitivity_analysis", "common.jl"))
include(joinpath(SRC_DIR, "sensitivity_analysis", "samples.jl"))

config_path = joinpath(dirname(SRC_DIR), "config.toml")
config = TOML.parsefile(config_path)
RME_PATH = config["calibration"]["domains"]["rme_domain"]
CALIB_PARAMS_PATH = config["calibration"]["products"]["calib_params"]

sa_config = SAConfig()

# * Domain setup - identical to 01_run_sa.jl, so model_spec(dom) reflects the same active
# factors and bounds the real sensitivity analysis run used.
dom = ADRIA.load_domain(
    RMEDomain, RME_PATH, sa_config.scenario_ssp;
    timeframe=Tuple(sa_config.timeframe),
    force_single_reef=true,
    calib_params_fn=CALIB_PARAMS_PATH
)
ADRIA.deactivate_interventions!(dom)
ADRIA.fix_factor!(dom, :wave_scenario, 0)
ADRIA.fix_factor!(dom, :cyclone_mortality_scenario, 0)
ADRIA.fix_factor!(dom, :dhw_scenario, 1)

ms = ADRIA.model_spec(dom)
dst_mean_factors = ms[occursin.(Ref("dist_mean"), string.(ms.fieldname)), :fieldname]
ADRIA.set_factor_bounds!.(Ref(dom), dst_mean_factors, Ref(Tuple(sa_config.dist_mean_bounds)))

ms = ADRIA.model_spec(dom)

function bound_of(ms, fieldname::Symbol)::Tuple{Float64,Float64}
    row = ms[ms.fieldname.==fieldname, :]
    isempty(row) && error("Factor $fieldname not found in model_spec(dom)")
    return (row.lower_bound[1], row.upper_bound[1])
end

heritability_bounds = bound_of(ms, :heritability)
dist_mean_bounds = bound_of(ms, dst_mean_factors[1])

# * Manually-added SA factors (not part of ADRIA's own model_spec) - bounds come straight
# from SAConfig/samples.jl defaults, exactly as passed to add_k_area!/add_depth_med!/
# add_dhw!/add_initial_cover! in 01_run_sa.jl.
k_area_bounds = Tuple(sa_config.k_area_range)
depth_bounds = Tuple(sa_config.depth_range)
dhw_bounds = (
    minimum(minimum.(sa_config.dhw_ranges)),
    maximum(maximum.(sa_config.dhw_ranges))
)

# Initial coral composition: each functional group's sampled weight is a raw combinatorial
# integer (see initial_coral_composition_scenarios()), normalized to a proportion of total
# cover only at model-run time - the biologically meaningful quantity Table S11 describes.
icc_scens = initial_coral_composition_scenarios()
icc_normalized = icc_scens ./ sum(icc_scens, dims=2)
icc_bounds = extrema(icc_normalized)

@assert sa_config.init_cover_range[1] == sa_config.init_cover_range[2] (
    "sa_config.init_cover_range is $(sa_config.init_cover_range), no longer a fixed value - " *
    "Table S11's removal of the Initial relative cover row (and the manuscript text noting " *
    "it was held fixed) need revisiting to describe it as a sampled range again."
)
init_cover_fixed = sa_config.init_cover_range[1]

sa_factors = Dict{String,Any}(
    "heritability_lo" => heritability_bounds[1],
    "heritability_hi" => heritability_bounds[2],
    "dist_mean_lo" => dist_mean_bounds[1],
    "dist_mean_hi" => dist_mean_bounds[2],
    "k_area_lo" => k_area_bounds[1],
    "k_area_hi" => k_area_bounds[2],
    "depth_lo" => depth_bounds[1],
    "depth_hi" => depth_bounds[2],
    "dhw_lo" => dhw_bounds[1],
    "dhw_hi" => dhw_bounds[2],
    "icc_lo" => round(icc_bounds[1]; digits=2),
    "icc_hi" => round(icc_bounds[2]; digits=2),
    "init_cover_fixed" => init_cover_fixed,
)

sa_factors_path = joinpath(dirname(SRC_DIR), "outputs", "sensitivity_analysis_factors_data.jl")
open(sa_factors_path, "w") do io
    println(io, "# Generated by src/outcomes/sensitivity_analysis_factors.jl - do not edit by hand.")
    println(io, "sa_factors = Dict{String,Any}(")
    for (k, v) in sort(collect(sa_factors); by=first)
        println(io, "    \"$k\" => $(repr(v)),")
    end
    println(io, ")")
end
@info "Wrote $sa_factors_path"
