using ADRIA
using LinearAlgebra
using Statistics
using TOML

using CoralBloxCalib
using CoralBloxCalib.common

# * Load calibration domain and calibrated model run
# Mirrors src/main.jl's setup (kept separate rather than `include`d so this script stays a
# lightweight timing-only entry point, without main.jl's plotting side effects). Reuses the
# calibrated domain/init cover already produced by the calibration repo - this script never
# runs the calibration itself, it only times one forward simulation of that domain, which is
# the unit of work repeated at every scenario evaluation during calibration.
config_path = joinpath(dirname(dirname(@__DIR__)), "config.toml")
config = load_config(config_path)

products = TOML.parsefile(config_path)["calibration"]["products"]
CALIB_PARAMS_FN = products["calib_params"]
INIT_COVER_FN = products["init_cover"]
for fn in (CALIB_PARAMS_FN, INIT_COVER_FN)
    isfile(fn) || error("Missing calibration product $fn - run the calibration first.")
end

dom = load_domain(config; calib_params_fn=CALIB_PARAMS_FN)

init_cover_da = open_dataset(INIT_COVER_FN).init_coral_cover
@assert size(init_cover_da) == size(dom.init_coral_cover) (
    "$INIT_COVER_FN is $(size(init_cover_da)) but the domain expects " *
    "$(size(dom.init_coral_cover)) - it was written for a different domain."
)
dom.init_coral_cover .= Array(init_cover_da)

scen = ADRIA.param_table(dom)

# * Single-core, single-thread timing of one full domain run (all reefs x full timeframe).
# `ADRIA.run_model(domain, param_set::DataFrameRow)` (the single-scenario method used below)
# has no internal `Threads.@threads` of its own - only `ADRIA.run_scenarios`, used for
# batches of scenarios, threads across scenarios - so `Threads.nthreads()` doesn't change
# this run's cost. BLAS can still parallelize linear algebra across cores under the hood
# though, so it's pinned to 1 here for a genuine single-core estimate.
BLAS.set_num_threads(1)

if Threads.nthreads() > 1
    @warn "Julia was started with $(Threads.nthreads()) threads. This does not affect " *
          "the single-scenario `run_model` call timed below, but start Julia with `-t 1` " *
          "if you want a strictly single-thread *process* for this estimate."
end

# Warm-up run: pay for JIT compilation outside the timed runs.
ADRIA.run_model(dom, scen[1, :]; apply_allee_effect=false)

n_reps = 10
times_s = [@elapsed(ADRIA.run_model(dom, scen[1, :]; apply_allee_effect=false)) for _ in 1:n_reps]
mean_s = mean(times_s)
std_s = std(times_s)

@info "Single model run timing (single-core, single-thread)" n_reps times_s mean_s std_s

# * Merge into the shared scores file rather than writing our own - it's shared with
# src/outcomes/calibration_scores.jl, which owns the file's other ("rmse_*"/"srcc_*"/etc.)
# keys and reads paper.qmd's include of the same file.
scores_path = joinpath(dirname(dirname(@__DIR__)), "outputs", "manuscript_metrics_data.jl")
existing_scores = if isfile(scores_path)
    m = Module()
    Base.include(m, scores_path)
    m.scores
else
    Dict{String,Any}()
end
merged_scores = merge(existing_scores, Dict{String,Any}(
    "single_run_n_reps" => n_reps,
    "single_run_mean_s" => mean_s,
    "single_run_std_s" => std_s,
))

open(scores_path, "w") do io
    println(io, "# Generated by src/outcomes/calibration_scores.jl and src/outcomes/single_run_timing.jl - do not edit by hand.")
    println(io, "scores = Dict{String,Any}(")
    for (k, v) in sort(collect(merged_scores); by=first)
        println(io, "    \"$k\" => $(repr(v)),")
    end
    println(io, ")")
end
@info "Wrote $scores_path"
