# Generated by src/outcomes/sensitivity_analysis_factors.jl - do not edit by hand.
sa_factors = Dict{String,Any}(
    "depth_hi" => 26.4,
    "depth_lo" => 0.0,
    "dhw_hi" => 30,
    "dhw_lo" => 0,
    "dist_mean_hi" => 10.0,
    "dist_mean_lo" => 3.0,
    "heritability_hi" => 0.5,
    "heritability_lo" => 0.25,
    "icc_hi" => 0.56,
    "icc_lo" => 0.05,
    "init_cover_fixed" => 0.3,
    "k_area_hi" => 1.0,
    "k_area_lo" => 0.0,
)
